```{r}
# import libraries
library(dplyr)

```
```{r}
mpg_df <- read.csv("MechaCar_mpg.csv")
head(mpg_df)

```
```{r}
# create linear model
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mpg_df) 

# generate summary statistics
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mpg_df)) 

```
```{r}
# Deliverable 2

# Read in data
Suspension <- read.csv(file='Suspension_coil.csv',check.names=F,stringsAsFactors = F)
```


```{r}
# Get PSI mean, median, variance, and standard deviation .
Mean = mean(Suspension$PSI)
Median=median(Suspension$PSI)
Variance=var(Suspension$PSI)
SD = sd(Suspension$PSI)

# Create total summary
total_Summary <- data.frame(Mean,Median,Variance,SD)
```
```{r}
# Create lot summary
lot_demo <- Suspension %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI), SD=sd(PSI), .groups = 'keep')

```


```{r}
# Deliverable 3
# Perform t-test across all lots
t.test(Suspension$PSI,mu = 1500)
```
```{r}
# Perform t-test for lot 1
t.test(subset(Suspension,Manufacturing_Lot=="Lot1")$PSI,mu = 1500)
```

```{r}
# Perform t-test on lot 2
t.test(subset(Suspension,Manufacturing_Lot=="Lot2")$PSI,mu = 1500)
```
```{r}
# Perform t-test on lot 3
t.test(subset(Suspension,Manufacturing_Lot=="Lot3")$PSI,mu = 1500)
```

